# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 20:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='idno',
            field=models.CharField(default=datetime.datetime(2016, 9, 29, 20, 30, 10, 886470, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
