# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_auto_20160929_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='idno',
            field=models.CharField(default=datetime.datetime(2016, 9, 29, 20, 53, 59, 857245, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
