# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0005_auto_20160930_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default=datetime.datetime(2016, 9, 30, 10, 17, 31, 922048, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
